services:
  app:
    build:
      context: ./
      args:
        RAILS_ENV: development
    command: ./bin/dev
    volumes:
      - .:/app # bind mount source code
      - bundle_cache:/bundle
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      BIND: tcp://0.0.0.0:3000
      RAILS_MAX_THREADS: "12"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`exercises.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.services.app.loadbalancer.healthcheck.path=/up"
      - "traefik.http.services.app.loadbalancer.healthcheck.interval=5s"

  worker:
    build:
      context: ./
      args:
        RAILS_ENV: development
    volumes:
      - .:/app
      - bundle_cache:/bundle
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      RAILS_MAX_THREADS: "12"
    command: bundle exec sidekiq -C config/sidekiq.yml

  proxy:
    image: traefik:v3.4
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 80:80
      - 8080:8080 # for Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: exercises_development
      POSTGRES_USER: exercises
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
  bundle_cache:
