/**
 * Typed wrapper over window.AppRoutes, which is generated by the Rails
 * application layout using URL helpers (source of truth: config/routes.rb).
 *
 * Base paths (non-parametric) come directly from Rails.
 * Parametric paths are composed from the base paths so that the root prefix
 * (/app today, app.leatherarmor.io later) is always inherited automatically.
 */

interface AppRoutes {
  appBase: string
  mainUrl: string
  login: string
  logout: string
  currentUser: string
  sheets: string
  adventures: string
  newAdventure: string
  stories: string
  featDefinitions: string
  spellDefinitions: string
  itemDefinitions: string
  featureFlags: string
  onboardingComplete: string
}

declare global {
  interface Window {
    AppRoutes: AppRoutes
  }
}

const base = window.AppRoutes

export const routes = {
  // ── Static paths (from Rails helpers) ───────────────────────
  mainUrl:           base.mainUrl,
  login:             base.login,
  logout:            base.logout,
  currentUser:       base.currentUser,
  // OmniAuth is under /app/auth — derives from appBase so it follows
  // the same context-aware prefix as every other player route.
  googleAuth:        `${base.appBase}/auth/google_oauth2`,
  sheets:            base.sheets,
  adventures:        base.adventures,
  newAdventure:      base.newAdventure,
  stories:           base.stories,
  featDefinitions:   base.featDefinitions,
  spellDefinitions:  base.spellDefinitions,
  itemDefinitions:   base.itemDefinitions,
  featureFlags:      base.featureFlags,
  onboardingComplete: base.onboardingComplete,

  // ── Parametric paths (composed from base paths) ──────────────
  sheet:             (id: number | string) => `${base.sheets}/${id}`,

  adventure:         (id: number | string) => `${base.adventures}/${id}`,
  adventureJson:     (id: number | string) => `${base.adventures}/${id}.json`,

  adventureMessages:    (id: number | string) => `${base.adventures}/${id}/messages`,
  adventureRoll:        (id: number | string) => `${base.adventures}/${id}/messages/roll`,
  adventureInitiative:  (id: number | string) => `${base.adventures}/${id}/messages/initiative`,

  adventureSheet:           (id: number | string) => `${base.adventures}/${id}/adventure_sheet`,
  adventureSheetToggleEquip:(id: number | string) => `${base.adventures}/${id}/adventure_sheet/toggle_equip`,
} as const
