/**
 * Pathfinder 1e Core Rulebook — Evocation Spells (Level 0–1).
 * All content is Open Game Content — mechanical rules only.
 */

import { SpellDefinition } from './pathfinder_spells_types';

export const EVOCATION_SPELLS: SpellDefinition[] = [
  // ─── Level 0 ───────────────────────────────────────────────

  {
    id: 'dancing_lights',
    name: 'Dancing Lights',
    school: 'evocation',
    descriptors: ['light'],
    classLevels: { bard: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: '1 minute',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Create up to 4 torch-like lights or 1 vaguely humanoid glowing shape. Lights move as you direct (move action). Each sheds light as a torch.' },
    ],
    summary: 'Create up to 4 hovering lights (torch brightness) that you direct.',
  },
  {
    id: 'flare',
    name: 'Flare',
    school: 'evocation',
    descriptors: ['light'],
    classLevels: { bard: 0, druid: 0, sorcerer: 0, wizard: 0 },
    components: ['V'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Fortitude negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'dazzled', duration: '1 minute' },
    ],
    summary: 'Flash of light dazzles one creature for 1 minute (Fort negates).',
  },
  {
    id: 'light',
    name: 'Light',
    school: 'evocation',
    descriptors: ['light'],
    classLevels: { bard: 0, cleric: 0, druid: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Touched object glows like a torch (20-ft radius normal light, 20-ft dim light beyond that).' },
    ],
    summary: 'Object sheds torchlight (20-ft radius) for 10 min/level.',
  },
  {
    id: 'ray_of_frost',
    name: 'Ray of Frost',
    school: 'evocation',
    descriptors: ['cold'],
    classLevels: { sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: true,
    effects: [
      { type: 'damage', dice: '1d3', damageType: 'cold' },
    ],
    summary: 'Ranged touch attack deals 1d3 cold damage.',
  },
  {
    id: 'spark',
    name: 'Spark',
    school: 'evocation',
    descriptors: ['fire'],
    classLevels: { bard: 0, cleric: 0, druid: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Fortitude negates (object)',
    spellResistance: true,
    effects: [
      { type: 'utility', description: 'Ignite unattended Fine flammable object (candle, tinder, etc.).' },
    ],
    summary: 'Ignite one unattended Fine flammable object.',
  },

  // ─── Level 1 ───────────────────────────────────────────────

  {
    id: 'burning_hands',
    name: 'Burning Hands',
    school: 'evocation',
    descriptors: ['fire'],
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Reflex half',
    spellResistance: true,
    effects: [
      { type: 'damage', dice: '1d4', damageType: 'fire', perCasterLevel: true, maxDice: 5 },
      { type: 'area', shape: 'cone', size: '15 ft', effect: 'All creatures in area take fire damage.' },
    ],
    summary: '15-ft cone deals 1d4/level fire damage (max 5d4). Reflex half.',
  },
  {
    id: 'divine_favor',
    name: 'Divine Favor',
    school: 'evocation',
    classLevels: { cleric: 1, paladin: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '1 minute',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'attack_bonus', bonus: '+1 per 3 CL (max +3)', bonusType: 'luck' },
      { type: 'damage_bonus', bonus: '+1 per 3 CL (max +3)', damageType: 'luck' },
    ],
    summary: '+1 luck bonus to attack and damage per 3 CL (max +3).',
  },
  {
    id: 'floating_disk',
    name: 'Floating Disk',
    school: 'evocation',
    descriptors: ['force'],
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 hour/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Create a 3-ft diameter disk of force that floats 3 ft off the ground and follows you. Carries up to 100 lbs/level.' },
    ],
    summary: 'Create a floating disk that carries up to 100 lbs/level.',
  },
  {
    id: 'magic_missile',
    name: 'Magic Missile',
    school: 'evocation',
    descriptors: ['force'],
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: true,
    effects: [
      { type: 'damage', dice: '1d4+1', damageType: 'force', missileCount: { base: 1, perLevels: 2, max: 5 } },
    ],
    summary: '1 missile (1d4+1 force) at CL 1, +1 missile per 2 CL (max 5 missiles). Auto-hit.',
  },
  {
    id: 'magic_stone',
    name: 'Magic Stone',
    school: 'evocation',
    classLevels: { cleric: 1, druid: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '30 minutes or until discharged',
    savingThrow: 'Will negates (harmless, object)',
    spellResistance: true,
    effects: [
      { type: 'damage_bonus', bonus: '+1 (or 2d6+2 vs undead)', damageType: 'bludgeoning' },
    ],
    summary: 'Up to 3 pebbles gain +1 to attack/damage (2d6+2 vs undead).',
  },
  {
    id: 'magic_weapon',
    name: 'Magic Weapon',
    school: 'evocation',
    classLevels: { cleric: 1, paladin: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless, object)',
    spellResistance: true,
    effects: [
      { type: 'attack_bonus', bonus: 1, bonusType: 'enhancement' },
      { type: 'damage_bonus', bonus: '+1', damageType: 'enhancement' },
    ],
    summary: 'Weapon gains +1 enhancement bonus to attack and damage.',
  },
  {
    id: 'produce_flame',
    name: 'Produce Flame',
    school: 'evocation',
    descriptors: ['fire'],
    classLevels: { druid: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'personal (or close for ranged touch)',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: true,
    effects: [
      { type: 'damage', dice: '1d6', damageType: 'fire', perCasterLevel: true, maxDice: 5 },
      { type: 'utility', description: 'Flames appear in your hand, providing light as a torch. Touch attack or throw as ranged touch (close range).' },
    ],
    summary: 'Flames in hand deal 1d6 + 1/level (max +5) fire. Use as touch or ranged touch.',
  },
  {
    id: 'shocking_grasp',
    name: 'Shocking Grasp',
    school: 'evocation',
    descriptors: ['electricity'],
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: true,
    effects: [
      { type: 'damage', dice: '1d6', damageType: 'electricity', perCasterLevel: true, maxDice: 5 },
      { type: 'special', description: '+3 attack bonus vs opponents wearing metal armor or made of metal.' },
    ],
    summary: 'Touch deals 1d6/level electricity (max 5d6). +3 attack vs metal armor/creatures.',
  },
  {
    id: 'sound_burst',
    name: 'Sound Burst',
    school: 'evocation',
    descriptors: ['sonic'],
    classLevels: { bard: 2, cleric: 2 },
    components: ['V', 'S', 'F', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Fortitude partial',
    spellResistance: true,
    effects: [
      { type: 'damage', dice: '1d8', damageType: 'sonic' },
      { type: 'condition', condition: 'stunned for 1 round (Fort negates stun)' },
    ],
    summary: '10-ft spread: 1d8 sonic damage. Fort or stunned 1 round.',
  },
];
