/**
 * Pathfinder 1e Core Rulebook — Transmutation Spells (Level 0–1).
 * All content is Open Game Content — mechanical rules only.
 */

import { SpellDefinition } from './pathfinder_spells_types';

export const TRANSMUTATION_SPELLS: SpellDefinition[] = [
  // ─── Level 0 ───────────────────────────────────────────────

  {
    id: 'arcane_mark',
    name: 'Arcane Mark',
    school: 'universal',
    classLevels: { sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: 'permanent',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Inscribe a personal rune or mark (up to 6 characters). Can be visible or invisible.' },
    ],
    summary: 'Inscribe a personal rune or mark on an object or surface.',
  },
  {
    id: 'mage_hand',
    name: 'Mage Hand',
    school: 'transmutation',
    classLevels: { bard: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Telekinetically move one non-magical object up to 5 lbs. Move 15 ft per round. Cannot attack, activate magic items, or carry creatures.' },
    ],
    summary: 'Move one object up to 5 lbs at a distance (15 ft/round).',
  },
  {
    id: 'mending',
    name: 'Mending',
    school: 'transmutation',
    classLevels: { bard: 0, cleric: 0, druid: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '10 minutes',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Will negates (harmless, object)',
    spellResistance: true,
    effects: [
      { type: 'utility', description: 'Repair one break or tear in an object (up to 1 lb). Does not restore magical properties.' },
    ],
    summary: 'Repair one break or tear in an object up to 1 lb.',
  },
  {
    id: 'message',
    name: 'Message',
    school: 'transmutation',
    descriptors: ['language-dependent'],
    classLevels: { bard: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S', 'F'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: '10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Whisper a message that only designated creatures (1 per CL) can hear. They can whisper back.' },
    ],
    summary: 'Whisper conversations at distance with designated creatures.',
  },
  {
    id: 'open_close',
    name: 'Open/Close',
    school: 'transmutation',
    classLevels: { bard: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S', 'F'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Will negates (object)',
    spellResistance: true,
    effects: [
      { type: 'utility', description: 'Open or close a door, chest, box, window, bag, pouch, bottle, barrel, or similar container (up to 30 lbs or with a simple latch). Cannot open locked items.' },
    ],
    summary: 'Remotely open or close one small unlocked object.',
  },
  {
    id: 'purify_food_and_drink',
    name: 'Purify Food and Drink',
    school: 'transmutation',
    classLevels: { cleric: 0, druid: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'Will negates (object)',
    spellResistance: true,
    effects: [
      { type: 'utility', description: 'Purify 1 cu. ft./level of food and water, rendering it free of poison, disease, and rot.' },
    ],
    summary: 'Make contaminated food and water pure and suitable for consumption.',
  },
  {
    id: 'virtue',
    name: 'Virtue',
    school: 'transmutation',
    classLevels: { cleric: 0, druid: 0, paladin: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 minute',
    savingThrow: 'none (harmless)',
    spellResistance: true,
    effects: [
      { type: 'temp_hp', amount: '1' },
    ],
    summary: 'Subject gains 1 temporary hit point for 1 minute.',
  },

  // ─── Level 1 ───────────────────────────────────────────────

  {
    id: 'animate_rope',
    name: 'Animate Rope',
    school: 'transmutation',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: '1 round/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Animate a rope (up to 50 ft + 5 ft/level) to coil, knot, loop, or entangle. Entangle: CMB = 10 + CL.' },
    ],
    summary: 'Animate a rope to coil, knot, or entangle (CMB = 10 + CL).',
  },
  {
    id: 'enlarge_person',
    name: 'Enlarge Person',
    school: 'transmutation',
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 round',
    range: 'close',
    duration: '1 min/level',
    savingThrow: 'Fortitude negates',
    spellResistance: true,
    effects: [
      { type: 'ability_modifier', ability: 'strength', bonus: 2, bonusType: 'size' },
      { type: 'ability_modifier', ability: 'dexterity', bonus: -2, bonusType: 'size' },
      { type: 'special', description: 'Humanoid target grows one size category. +2 size STR, -2 size DEX, -1 attack/AC (size), +1 CMB/CMD.' },
    ],
    summary: 'Grow one size. +2 STR, -2 DEX, -1 attack/AC, +1 CMB/CMD.',
  },
  {
    id: 'entangle',
    name: 'Entangle',
    school: 'transmutation',
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'long',
    duration: '1 min/level',
    savingThrow: 'Reflex partial',
    spellResistance: false,
    effects: [
      { type: 'area', shape: 'spread', size: '40-ft radius', effect: 'Plants entangle creatures in area. Entangled creatures are -2 attack, -4 DEX. Reflex to avoid being stuck (immobile). DC 20 STR or Escape Artist to break free each round.' },
    ],
    summary: '40-ft radius: plants entangle. -2 attack, -4 DEX. Reflex or stuck.',
  },
  {
    id: 'erase',
    name: 'Erase',
    school: 'transmutation',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'none (see text)',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Erase nonmagical writing from a surface (2 pages). Magical writing: CL check DC 15.' },
    ],
    summary: 'Erase mundane or magical writing from a surface.',
  },
  {
    id: 'expeditious_retreat',
    name: 'Expeditious Retreat',
    school: 'transmutation',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'special', description: 'Base land speed increases by 30 ft (enhancement bonus). Does not affect other movement types.' },
    ],
    summary: '+30 ft enhancement bonus to base land speed.',
  },
  {
    id: 'feather_fall',
    name: 'Feather Fall',
    school: 'transmutation',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V'],
    castingTime: '1 immediate action',
    range: 'close',
    duration: 'until landing or 1 round/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'special', description: 'Up to 1 creature/level falls slowly (60 ft per round). Take no falling damage on landing.' },
    ],
    summary: 'Up to 1 creature/level falls slowly, taking no falling damage.',
  },
  {
    id: 'goodberry',
    name: 'Goodberry',
    school: 'transmutation',
    classLevels: { druid: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 day/level',
    savingThrow: 'none',
    spellResistance: true,
    effects: [
      { type: 'healing', dice: '1', bonusPerLevel: 0, maxBonus: 0 },
      { type: 'utility', description: 'Transmute 2d4 fresh berries so each cures 1 HP (max 8 HP total). Also provides nourishment as a full meal.' },
    ],
    summary: '2d4 berries each heal 1 HP and nourish as a full meal.',
  },
  {
    id: 'jump',
    name: 'Jump',
    school: 'transmutation',
    classLevels: { druid: 1, ranger: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'skill_bonus', skill: 'Acrobatics', bonus: 10, bonusType: 'enhancement' },
      { type: 'special', description: '+10 enhancement to Acrobatics for jumping (+20 at CL 5, +30 at CL 9).' },
    ],
    summary: '+10/+20/+30 enhancement bonus to Acrobatics for jumping.',
  },
  {
    id: 'longstrider',
    name: 'Longstrider',
    school: 'transmutation',
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '1 hour/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'special', description: 'Base speed increases by 10 ft (enhancement bonus).' },
    ],
    summary: '+10 ft enhancement bonus to base speed.',
  },
  {
    id: 'magic_fang',
    name: 'Magic Fang',
    school: 'transmutation',
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'attack_bonus', bonus: 1, bonusType: 'enhancement', condition: 'one natural weapon' },
      { type: 'damage_bonus', bonus: '+1', damageType: 'enhancement', condition: 'one natural weapon' },
    ],
    summary: "One natural weapon gains +1 enhancement to attack and damage.",
  },
  {
    id: 'reduce_person',
    name: 'Reduce Person',
    school: 'transmutation',
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 round',
    range: 'close',
    duration: '1 min/level',
    savingThrow: 'Fortitude negates',
    spellResistance: true,
    effects: [
      { type: 'ability_modifier', ability: 'strength', bonus: -2, bonusType: 'size' },
      { type: 'ability_modifier', ability: 'dexterity', bonus: 2, bonusType: 'size' },
      { type: 'special', description: 'Humanoid target shrinks one size category. -2 size STR, +2 size DEX, +1 attack/AC (size), -1 CMB/CMD.' },
    ],
    summary: 'Shrink one size. -2 STR, +2 DEX, +1 attack/AC, -1 CMB/CMD.',
  },
  {
    id: 'shillelagh',
    name: 'Shillelagh',
    school: 'transmutation',
    classLevels: { druid: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless, object)',
    spellResistance: true,
    effects: [
      { type: 'special', description: 'A non-magical club or quarterstaff you hold is enhanced: +1 enhancement to attack/damage and damage dice increase by two steps (club to 1d10, quarterstaff to 2d6).' },
    ],
    summary: 'Club/quarterstaff gains +1 and damage dice increase two steps.',
  },
];
