/**
 * Pathfinder 1e Core Rulebook — Conjuration Spells (Level 0–1).
 * All content is Open Game Content — mechanical rules only.
 */

import { SpellDefinition } from './pathfinder_spells_types';

export const CONJURATION_SPELLS: SpellDefinition[] = [
  // ─── Level 0 ───────────────────────────────────────────────

  {
    id: 'acid_splash',
    name: 'Acid Splash',
    school: 'conjuration',
    subschool: 'creation',
    descriptors: ['acid'],
    classLevels: { sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'damage', dice: '1d3', damageType: 'acid' },
    ],
    summary: 'Ranged touch attack deals 1d3 acid damage.',
  },
  {
    id: 'create_water',
    name: 'Create Water',
    school: 'conjuration',
    subschool: 'creation',
    descriptors: ['water'],
    classLevels: { cleric: 0, druid: 0, paladin: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Create up to 2 gallons of water per caster level.' },
    ],
    summary: 'Create 2 gallons of pure water per caster level.',
  },

  // ─── Level 1 ───────────────────────────────────────────────

  {
    id: 'bless_water',
    name: 'Bless Water',
    school: 'conjuration',
    subschool: 'creation',
    descriptors: ['good'],
    classLevels: { cleric: 1, paladin: 1 },
    components: ['V', 'S', 'M'],
    materialComponent: 'silver powder (25 gp)',
    castingTime: '1 minute',
    range: 'touch',
    duration: 'instantaneous',
    savingThrow: 'Will negates (object)',
    spellResistance: true,
    effects: [
      { type: 'utility', description: 'Turn a flask of water into holy water. Holy water deals 2d4 damage to undead or evil outsiders on a direct hit.' },
    ],
    summary: 'Create holy water (2d4 damage to undead/evil outsiders).',
  },
  {
    id: 'cure_light_wounds',
    name: 'Cure Light Wounds',
    school: 'conjuration',
    subschool: 'healing',
    classLevels: { bard: 1, cleric: 1, druid: 1, paladin: 1, ranger: 2 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: 'instantaneous',
    savingThrow: 'Will half (harmless)',
    spellResistance: true,
    effects: [
      { type: 'healing', dice: '1d8', bonusPerLevel: 1, maxBonus: 5 },
    ],
    summary: 'Heals 1d8 + 1/caster level (max +5) HP.',
  },
  {
    id: 'curse_water',
    name: 'Curse Water',
    school: 'conjuration',
    subschool: 'creation',
    descriptors: ['evil'],
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'M'],
    materialComponent: 'silver powder (25 gp)',
    castingTime: '1 minute',
    range: 'touch',
    duration: 'instantaneous',
    savingThrow: 'Will negates (object)',
    spellResistance: true,
    effects: [
      { type: 'utility', description: 'Turn a flask of water into unholy water. Unholy water deals 2d4 damage to good outsiders on a direct hit.' },
    ],
    summary: 'Create unholy water (2d4 damage to good outsiders).',
  },
  {
    id: 'grease',
    name: 'Grease',
    school: 'conjuration',
    subschool: 'creation',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 min/level',
    savingThrow: 'Reflex (see text)',
    spellResistance: false,
    effects: [
      { type: 'area', shape: 'square', size: '10 ft', effect: 'Covers ground or object in slippery grease. Creatures in area must save or fall prone. Moving through requires Acrobatics DC 10.' },
    ],
    summary: 'Cover area or object in grease. Creatures must save or fall.',
  },
  {
    id: 'mage_armor',
    name: 'Mage Armor',
    school: 'conjuration',
    subschool: 'creation',
    descriptors: ['force'],
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'F'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 hour/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: false,
    effects: [
      { type: 'ac_bonus', bonus: 4, bonusType: 'armor' },
    ],
    summary: '+4 armor bonus to AC (force effect, no max DEX, no ACP, no ASF).',
  },
  {
    id: 'mount',
    name: 'Mount',
    school: 'conjuration',
    subschool: 'summoning',
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 round',
    range: 'close',
    duration: '2 hours/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'summon', creature: 'light horse or pony', count: '1' },
    ],
    summary: 'Summon a light horse or pony to serve as a mount.',
  },
  {
    id: 'obscuring_mist',
    name: 'Obscuring Mist',
    school: 'conjuration',
    subschool: 'creation',
    classLevels: { cleric: 1, druid: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'area', shape: 'spread', size: '20-ft radius, 20 ft high', effect: 'Fog grants concealment (20% miss chance) to creatures within. Creatures 5+ ft away have concealment; beyond that total concealment.' },
    ],
    summary: 'Create a cloud of mist that grants concealment.',
  },
  {
    id: 'summon_monster_i',
    name: 'Summon Monster I',
    school: 'conjuration',
    subschool: 'summoning',
    classLevels: { bard: 1, cleric: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'F', 'DF'],
    castingTime: '1 round',
    range: 'close',
    duration: '1 round/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'summon', creature: 'one creature from the 1st-level summon list', count: '1' },
    ],
    summary: 'Summon one extraplanar creature from the 1st-level list.',
  },
  {
    id: 'summon_natures_ally_i',
    name: "Summon Nature's Ally I",
    school: 'conjuration',
    subschool: 'summoning',
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 round',
    range: 'close',
    duration: '1 round/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'summon', creature: 'one animal from the 1st-level nature ally list', count: '1' },
    ],
    summary: 'Summon one natural creature from the 1st-level list.',
  },
  {
    id: 'unseen_servant',
    name: 'Unseen Servant',
    school: 'conjuration',
    subschool: 'creation',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 hour/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Create an invisible, mindless force that performs simple tasks (STR 2, can clean, carry, open doors). Cannot attack or be attacked.' },
    ],
    summary: 'Create an invisible servant to perform simple tasks.',
  },
];
