/**
 * Pathfinder 1e Core Rulebook — Enchantment Spells (Level 0–1).
 * All content is Open Game Content — mechanical rules only.
 */

import { SpellDefinition } from './pathfinder_spells_types';

export const ENCHANTMENT_SPELLS: SpellDefinition[] = [
  // ─── Level 0 ───────────────────────────────────────────────

  {
    id: 'daze',
    name: 'Daze',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['mind-affecting'],
    classLevels: { bard: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 round',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'dazed', hitDiceLimit: 4, duration: '1 round' },
    ],
    summary: 'Humanoid of 4 HD or fewer is dazed for 1 round (Will negates).',
  },
  {
    id: 'lullaby',
    name: 'Lullaby',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['mind-affecting'],
    classLevels: { bard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: 'concentration + 1 round/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'debuff', target: 'Perception', penalty: -5 },
      { type: 'save_bonus', save: 'all', bonus: -2, condition: 'vs sleep effects' },
    ],
    summary: 'Target has -5 Perception and -2 saves vs sleep effects.',
  },

  // ─── Level 1 ───────────────────────────────────────────────

  {
    id: 'bane',
    name: 'Bane',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['fear', 'mind-affecting'],
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 min/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'debuff', target: 'attack', penalty: -1 },
      { type: 'debuff', target: 'saves vs fear', penalty: -1 },
    ],
    summary: 'Enemies in 50-ft radius take -1 on attacks and -1 on saves vs fear.',
  },
  {
    id: 'bless',
    name: 'Bless',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['mind-affecting'],
    classLevels: { cleric: 1, paladin: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: true,
    effects: [
      { type: 'attack_bonus', bonus: 1, bonusType: 'morale' },
      { type: 'save_bonus', save: 'all', bonus: 1, bonusType: 'morale', condition: 'vs fear effects' },
    ],
    summary: 'Allies gain +1 morale on attacks and +1 morale on saves vs fear.',
  },
  {
    id: 'charm_animal',
    name: 'Charm Animal',
    school: 'enchantment',
    subschool: 'charm',
    descriptors: ['mind-affecting'],
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 hour/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'charmed (treats you as friendly; +5 to CHA-based checks to interact)' },
    ],
    summary: 'One animal treats you as a trusted friend (Will negates).',
  },
  {
    id: 'charm_person',
    name: 'Charm Person',
    school: 'enchantment',
    subschool: 'charm',
    descriptors: ['mind-affecting'],
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 hour/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'charmed (treats you as friendly; +5 to CHA-based checks to interact)' },
    ],
    summary: 'One humanoid treats you as a trusted friend (Will negates).',
  },
  {
    id: 'command',
    name: 'Command',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['language-dependent', 'mind-affecting'],
    classLevels: { cleric: 1 },
    components: ['V'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 round',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'special', description: 'Give one-word command (approach, drop, fall, flee, halt). Target obeys on its next turn. 6+ HD creatures are immune.' },
    ],
    summary: 'One-word command (approach/drop/fall/flee/halt). Will negates.',
  },
  {
    id: 'doom',
    name: 'Doom',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['fear', 'mind-affecting'],
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: '1 min/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'shaken' },
    ],
    summary: 'One creature becomes shaken (Will negates).',
  },
  {
    id: 'hideous_laughter',
    name: 'Hideous Laughter',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['mind-affecting'],
    classLevels: { bard: 1, sorcerer: 2, wizard: 2 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '1 round/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'prone and unable to act (laughing). Each round may attempt new save to end.' },
    ],
    summary: 'Subject falls prone laughing and cannot take actions (Will negates, new save each round).',
  },
  {
    id: 'hypnotism',
    name: 'Hypnotism',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['mind-affecting'],
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 round',
    range: 'close',
    duration: '2d4 rounds',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'fascinated', totalHDLimit: 4 },
    ],
    summary: 'Fascinate 2d4 HD of creatures (Will negates).',
  },
  {
    id: 'sleep',
    name: 'Sleep',
    school: 'enchantment',
    subschool: 'compulsion',
    descriptors: ['mind-affecting'],
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 round',
    range: 'medium',
    duration: '1 min/level',
    savingThrow: 'Will negates',
    spellResistance: true,
    effects: [
      { type: 'condition', condition: 'sleep (unconscious, can be awakened by damage or standard action)', totalHDLimit: 4 },
    ],
    summary: 'Put 4 HD of creatures to sleep (Will negates). Lowest HD affected first.',
  },
];
