/**
 * Pathfinder 1e Core Rulebook — Divination Spells (Level 0–1).
 * All content is Open Game Content — mechanical rules only.
 */

import { SpellDefinition } from './pathfinder_spells_types';

export const DIVINATION_SPELLS: SpellDefinition[] = [
  // ─── Level 0 ───────────────────────────────────────────────

  {
    id: 'detect_magic',
    name: 'Detect Magic',
    school: 'divination',
    classLevels: { bard: 0, cleric: 0, druid: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'magical auras', range: '60-ft cone' },
    ],
    summary: 'Detect magical auras in a 60-ft cone. Concentration reveals strength and school.',
  },
  {
    id: 'detect_poison',
    name: 'Detect Poison',
    school: 'divination',
    classLevels: { cleric: 0, druid: 0, paladin: 1, ranger: 1, sorcerer: 0, wizard: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'poison in one creature or object' },
    ],
    summary: 'Detect whether a creature, object, or area has been poisoned or is poisonous.',
  },
  {
    id: 'guidance',
    name: 'Guidance',
    school: 'divination',
    classLevels: { cleric: 0, druid: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 minute or until discharged',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'special', description: 'Subject gains +1 competence bonus on a single attack roll, saving throw, or skill check, then the spell ends.' },
    ],
    summary: '+1 competence bonus on one attack, save, or skill check.',
  },
  {
    id: 'know_direction',
    name: 'Know Direction',
    school: 'divination',
    classLevels: { bard: 0, druid: 0 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: 'instantaneous',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'You instantly know the direction of north from your current position.' },
    ],
    summary: 'Instantly know which direction is north.',
  },
  {
    id: 'read_magic',
    name: 'Read Magic',
    school: 'divination',
    classLevels: { bard: 0, cleric: 0, druid: 0, paladin: 1, ranger: 1, sorcerer: 0, wizard: 0 },
    components: ['V', 'S', 'F'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Read scrolls, spellbooks, and magical inscriptions that would otherwise be unintelligible.' },
    ],
    summary: 'Read magical writings (scrolls, spellbooks, inscriptions).',
  },

  // ─── Level 1 ───────────────────────────────────────────────

  {
    id: 'comprehend_languages',
    name: 'Comprehend Languages',
    school: 'divination',
    classLevels: { bard: 1, cleric: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Understand any spoken or written language (one page per minute for written). Does not grant ability to speak or write.' },
    ],
    summary: 'Understand all spoken and written languages.',
  },
  {
    id: 'deathwatch',
    name: 'Deathwatch',
    school: 'divination',
    classLevels: { cleric: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'living creatures: whether alive, wounded (at or below half HP), at -1 HP or below, dead, or undead', range: '30-ft cone' },
    ],
    summary: 'Determine HP status of creatures in range (alive, wounded, dying, dead, undead).',
  },
  {
    id: 'detect_animals_or_plants',
    name: 'Detect Animals or Plants',
    school: 'divination',
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'long',
    duration: 'concentration, up to 10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'animals or plants of a specific kind', range: 'long range cone' },
    ],
    summary: 'Detect a specific kind of animal or plant in range.',
  },
  {
    id: 'detect_chaos',
    name: 'Detect Chaos',
    school: 'divination',
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'chaotic auras (creatures, spells, objects)', range: '60-ft cone' },
    ],
    summary: 'Detect chaotic creatures, spells, and objects in a 60-ft cone.',
  },
  {
    id: 'detect_evil',
    name: 'Detect Evil',
    school: 'divination',
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'evil auras (creatures, spells, objects)', range: '60-ft cone' },
    ],
    summary: 'Detect evil creatures, spells, and objects in a 60-ft cone.',
  },
  {
    id: 'detect_good',
    name: 'Detect Good',
    school: 'divination',
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'good auras (creatures, spells, objects)', range: '60-ft cone' },
    ],
    summary: 'Detect good creatures, spells, and objects in a 60-ft cone.',
  },
  {
    id: 'detect_law',
    name: 'Detect Law',
    school: 'divination',
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'lawful auras (creatures, spells, objects)', range: '60-ft cone' },
    ],
    summary: 'Detect lawful creatures, spells, and objects in a 60-ft cone.',
  },
  {
    id: 'detect_secret_doors',
    name: 'Detect Secret Doors',
    school: 'divination',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'secret doors, compartments, and hidden caches', range: '60-ft cone' },
    ],
    summary: 'Detect secret doors and hidden compartments in a 60-ft cone.',
  },
  {
    id: 'detect_snares_and_pits',
    name: 'Detect Snares and Pits',
    school: 'divination',
    classLevels: { druid: 1, ranger: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 10 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'simple pits, deadfalls, snares, and mechanical traps (natural and primitive)', range: '60-ft cone' },
    ],
    summary: 'Detect natural/primitive traps in a 60-ft cone.',
  },
  {
    id: 'detect_undead',
    name: 'Detect Undead',
    school: 'divination',
    classLevels: { cleric: 1, paladin: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: 'concentration, up to 1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'detection', detects: 'undead creatures and their aura strength', range: '60-ft cone' },
    ],
    summary: 'Detect undead in a 60-ft cone. Reveals location and aura strength.',
  },
  {
    id: 'identify',
    name: 'Identify',
    school: 'divination',
    classLevels: { bard: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M'],
    materialComponent: 'wine stirred with an owl feather (100 gp)',
    castingTime: '1 standard action',
    range: 'close',
    duration: '3 rounds/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: '+10 enhancement bonus on Spellcraft checks to identify properties of magic items. Can attempt one Spellcraft check per round.' },
    ],
    summary: '+10 Spellcraft to identify magic item properties (1 check/round).',
  },
  {
    id: 'speak_with_animals',
    name: 'Speak with Animals',
    school: 'divination',
    classLevels: { bard: 3, druid: 1, ranger: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Communicate with animals. Ask questions and receive answers. Animals are not inherently friendly; Diplomacy or similar may be needed.' },
    ],
    summary: 'Communicate verbally with animals for the duration.',
  },
  {
    id: 'true_strike',
    name: 'True Strike',
    school: 'divination',
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'F'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: 'see text',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'attack_bonus', bonus: 20, bonusType: 'insight', condition: 'on your next single attack roll (must be before end of next turn)' },
    ],
    summary: '+20 insight bonus on your next attack roll.',
  },
];
