/**
 * Pathfinder 1e Core Rulebook — Abjuration Spells (Level 0–1).
 * All content is Open Game Content — mechanical rules only.
 */

import { SpellDefinition } from './pathfinder_spells_types';

export const ABJURATION_SPELLS: SpellDefinition[] = [
  // ─── Level 0 ───────────────────────────────────────────────

  {
    id: 'resistance',
    name: 'Resistance',
    school: 'abjuration',
    classLevels: { bard: 0, cleric: 0, druid: 0, sorcerer: 0, wizard: 0 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 minute',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'save_bonus', save: 'all', bonus: 1, bonusType: 'resistance' },
    ],
    summary: 'Subject gains +1 resistance bonus on saves for 1 minute.',
  },

  // ─── Level 1 ───────────────────────────────────────────────

  {
    id: 'alarm',
    name: 'Alarm',
    school: 'abjuration',
    classLevels: { bard: 1, ranger: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'F', 'DF'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '2 hours/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Wards an area (20-ft radius). Triggers mental or audible alarm when Tiny or larger creature enters.' },
    ],
    summary: 'Ward an area to alert you when creatures enter.',
  },
  {
    id: 'endure_elements',
    name: 'Endure Elements',
    school: 'abjuration',
    classLevels: { cleric: 1, druid: 1, paladin: 1, ranger: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '24 hours',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'immunity', target: 'nonlethal damage from hot or cold environments (-50°F to 140°F)' },
    ],
    summary: 'Subject protected from severe weather (hot and cold) for 24 hours.',
  },
  {
    id: 'hold_portal',
    name: 'Hold Portal',
    school: 'abjuration',
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V'],
    castingTime: '1 standard action',
    range: 'medium',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'utility', description: 'Holds door/portal shut as if securely locked (adds +5 to DC to force open).' },
    ],
    summary: 'Magically hold a door shut (+5 to break DC).',
  },
  {
    id: 'protection_from_chaos',
    name: 'Protection from Chaos',
    school: 'abjuration',
    descriptors: ['lawful'],
    classLevels: { cleric: 1, paladin: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: false,
    effects: [
      { type: 'deflection_ac', bonus: '2', bonusType: 'deflection' },
      { type: 'save_bonus', save: 'all', bonus: 2, bonusType: 'resistance', condition: 'vs chaotic creatures' },
      { type: 'immunity', target: 'mental control (new save with +2 morale bonus) from chaotic creatures' },
    ],
    summary: '+2 deflection AC, +2 saves vs chaotic; blocks mental control from chaotic sources.',
  },
  {
    id: 'protection_from_evil',
    name: 'Protection from Evil',
    school: 'abjuration',
    descriptors: ['good'],
    classLevels: { cleric: 1, paladin: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: false,
    effects: [
      { type: 'deflection_ac', bonus: '2', bonusType: 'deflection' },
      { type: 'save_bonus', save: 'all', bonus: 2, bonusType: 'resistance', condition: 'vs evil creatures' },
      { type: 'immunity', target: 'mental control (new save with +2 morale bonus) from evil creatures' },
    ],
    summary: '+2 deflection AC, +2 saves vs evil; blocks mental control from evil sources.',
  },
  {
    id: 'protection_from_good',
    name: 'Protection from Good',
    school: 'abjuration',
    descriptors: ['evil'],
    classLevels: { cleric: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: false,
    effects: [
      { type: 'deflection_ac', bonus: '2', bonusType: 'deflection' },
      { type: 'save_bonus', save: 'all', bonus: 2, bonusType: 'resistance', condition: 'vs good creatures' },
      { type: 'immunity', target: 'mental control (new save with +2 morale bonus) from good creatures' },
    ],
    summary: '+2 deflection AC, +2 saves vs good; blocks mental control from good sources.',
  },
  {
    id: 'protection_from_law',
    name: 'Protection from Law',
    school: 'abjuration',
    descriptors: ['chaotic'],
    classLevels: { cleric: 1, sorcerer: 1, wizard: 1 },
    components: ['V', 'S', 'M', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: false,
    effects: [
      { type: 'deflection_ac', bonus: '2', bonusType: 'deflection' },
      { type: 'save_bonus', save: 'all', bonus: 2, bonusType: 'resistance', condition: 'vs lawful creatures' },
      { type: 'immunity', target: 'mental control (new save with +2 morale bonus) from lawful creatures' },
    ],
    summary: '+2 deflection AC, +2 saves vs lawful; blocks mental control from lawful sources.',
  },
  {
    id: 'remove_fear',
    name: 'Remove Fear',
    school: 'abjuration',
    classLevels: { bard: 1, cleric: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'close',
    duration: '10 minutes (or special)',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'save_bonus', save: 'all', bonus: 4, bonusType: 'morale', condition: 'vs fear effects' },
      { type: 'special', description: 'If target is already under a fear effect, gets a new save with +4 morale bonus to suppress the fear.' },
    ],
    summary: '+4 morale bonus vs fear. Suppresses existing fear effects (new save).',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    school: 'abjuration',
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'DF'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 round/level',
    savingThrow: 'Will negates',
    spellResistance: false,
    effects: [
      { type: 'special', description: 'Any opponent attempting to directly attack the warded creature must make a Will save. On failure, the opponent cannot attack the creature for the duration. On success, the opponent can act normally. The spell ends if the warded creature attacks.' },
    ],
    summary: 'Opponents must save to attack warded creature. Ends if warded creature attacks.',
  },
  {
    id: 'shield',
    name: 'Shield',
    school: 'abjuration',
    classLevels: { sorcerer: 1, wizard: 1 },
    components: ['V', 'S'],
    castingTime: '1 standard action',
    range: 'personal',
    duration: '1 min/level',
    savingThrow: 'none',
    spellResistance: false,
    effects: [
      { type: 'ac_bonus', bonus: 4, bonusType: 'shield' },
      { type: 'immunity', target: 'magic missiles' },
    ],
    summary: '+4 shield bonus to AC. Immune to magic missile.',
  },
  {
    id: 'shield_of_faith',
    name: 'Shield of Faith',
    school: 'abjuration',
    classLevels: { cleric: 1 },
    components: ['V', 'S', 'M'],
    castingTime: '1 standard action',
    range: 'touch',
    duration: '1 min/level',
    savingThrow: 'Will negates (harmless)',
    spellResistance: true,
    effects: [
      { type: 'deflection_ac', bonus: '+2 (increases by 1 per 6 CL, max +5)', bonusType: 'deflection' },
    ],
    summary: '+2 deflection bonus to AC (increases with caster level, max +5).',
  },
];
